package com.example.demospringboot.po;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

/**
 * Table: user_info
 */
@Data
public class UserInfo implements Serializable {
    /**
     * Table:     user_info
     * Column:    uid
     * Nullable:  false
     */
    private Integer uid;

    /**
     * 账号
     *
     * Table:     user_info
     * Column:    user_name
     * Nullable:  true
     */
    private String userName;

    /**
     * 姓名
     *
     * Table:     user_info
     * Column:    name
     * Nullable:  true
     */
    private String name;

    /**
     * 密码
     *
     * Table:     user_info
     * Column:    password
     * Nullable:  true
     */
    private String password;

    /**
     * 加密密码的盐
     *
     * Table:     user_info
     * Column:    salt
     * Nullable:  true
     */
    private String salt;

    /**
     * 用户状态
     *
     * Table:     user_info
     * Column:    status
     * Nullable:  true
     */
    private Boolean status;

    /**
     * 创建时间
     *
     * Table:     user_info
     * Column:    create_time
     * Nullable:  true
     */
    private Date createTime;

    /**
     * 修改时间
     *
     * Table:     user_info
     * Column:    modify_time
     * Nullable:  true
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbggenerated Mon Mar 04 15:12:17 CST 2019
     */
    private static final long serialVersionUID = 1L;
}